name: test_task_card

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  get: ^4.6.6
  get_it: ^8.0.3
  camera: ^0.11.0+2
  nfc_manager: ^3.5.0
  flutter_animate: ^4.5.2
  toastification: ^2.3.0
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/